[project]
name = "braintrust-load-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "braintrust>=0.1.1",
    "faker>=37.3.0",
    "tiktoken>=0.9.0",
]
